# Generated by Django 5.0.6 on 2024-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_completed', models.IntegerField(default=0)),
                ('subjects_completed', models.JSONField(default=dict)),
            ],
        ),
    ]
