# Generated by Django 5.0.6 on 2024-07-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_achievement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
