# Generated by Django 5.0.6 on 2024-07-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('questions', models.JSONField(default=list)),
                ('score', models.IntegerField(default=-1)),
                ('grade', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
