# Generated by Django 5.0.6 on 2024-07-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
