# Generated by Django 5.0.6 on 2024-07-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
