# Generated by Django 5.0.6 on 2024-07-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='game',
            name='grade',
            field=models.JSONField(default=list),
        ),
    ]
